

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: bibliotech_db
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5426:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: bibliotech_db
      DB_USER: admin
      DB_PASS: adminpassword
    stdin_open: true 
    tty: true        